### ISSUE TITLE
Unable to load seninja in Binja 3.5.4526

### ISSUE THREAD

**Issue by vishwaraj101** [borzacchiello/seninja#15]
Error in log

`Failed to import python plugin: community/borzacchiello_seninja: cannot import name 'SidebarWidgetLocation' from 'binaryninjaui' (C:\Program Files\Vector35\BinaryNinja\plugins\..\python\binaryninjaui\__init__.py
`

**Comment by borzacchiello** [comment]
Hello!
Unfortunately, the last version of SENinja does support only Binary Ninja >= 4.0.
Please update binary ninja or clone an old commit of SENinja (e.g., 78e28aca018d5b0bcef85bdbe149b66e55024252),

**Comment by vishwaraj101** [comment]
Thanks for the prompt response , I tried the above commit it is still giving me the same error i tried all the releases as availale could you please help me here would really appreciate it ? I don't have version 4

**Comment by borzacchiello** [comment]
Uhm, that's strange.
Make sure to uninstall SENinja from the plugin manager before cloning the repo in the plugin folder!

**Comment by vishwaraj101** [comment]
did that still getting error this time below error

`[Default] Traceback (most recent call last):
[Default]   File "C:\Users\fuzzmachine\AppData\Roaming\Binary Ninja\plugins\seninja\__init__.py", line 31, in <module>
[Default]     from .ui.ui_manager import UIManager
[Default]   File "C:\Users\fuzzmachine\AppData\Roaming\Binary Ninja\plugins\seninja\ui\ui_manager.py", line 13, in <module>
[Default]     from .seninja_widget import SENinjaWidgetType
[Default]   File "C:\Users\fuzzmachine\AppData\Roaming\Binary Ninja\plugins\seninja\ui\seninja_widget.py", line 1, in <module>
[Default]     from binaryninjaui import (
[Default] ImportError: cannot import name 'SidebarWidgetLocation' from 'binaryninjaui' (C:\Users\fuzzmachine\AppData\Local\Vector35\BinaryNinja\plugins\..\python\binaryninjaui\__init__.py)
[PythonPlugin] Python plugin 'seninja' could not be loaded`

**Comment by borzacchiello** [comment]
Sorry, that commit requires Binary Ninja 4.0.
Try with this one: ee16031ab1df32561f3a23e23435706c1cdf724c

**Comment by vishwaraj101** [comment]
Awesome thanks a lot @borzacchiello it worked 🥳

**Comment by vishwaraj101** [comment]
@borzacchiello it will be cool if we can get some demo videos/tutorial on how to use seninja in binaries from the makers itself !!
