### ISSUE TITLE
Create plugin.json?

### ISSUE THREAD

**Issue by psifertex** [borzacchiello/seninja#2]
Am would you accept a PR with a Plugin.json which could be used to install this plugin via the BN plugin manager? More information on the process: 

https://binary.ninja/2019/07/04/plugin-manager-2.0.html

**Comment by borzacchiello** [comment]
Yes absolutely! I just pushed it, I hope that the format is correct.

**Comment by psifertex** [comment]
Almost there, one thing to fix is the embedded image has to be to the full raw url unfortunately since we're rendering the markdown to html and it doesn't have the original github url at that point. Those URLs look like: 

https://raw.githubusercontent.com/borzacchiello/seninja/master/pictures/screenshot.png

Alternatively, if you just take your current README as is, and convert the images similarly it'll make the preview in the plugin manager look the same as the github readme!

Then, once that's done, just create a release as described in the blog or use the [helper utility](https://github.com/Vector35/release_helper).

**Comment by borzacchiello** [comment]
plugin.json fixed, and release created. It should be fine now!

**Comment by psifertex** [comment]
Looks great, thanks! Added to the plugin manager.
