### ISSUE TITLE
create requirements.txt

### ISSUE THREAD

**Issue by psifertex** [borzacchiello/seninja#6]
Please create a [requirements.txt](https://pip.pypa.io/en/stable/cli/pip_install/#requirement-specifiers) instead of using https://github.com/borzacchiello/seninja/blob/master/plugin.json#L28

The Plugin manager will now automatically install dependencies if specified there.

**Comment by borzacchiello** [comment]
Done! I also updated to PySide6, now it works with the latest version of binary ninja (I was using the latest stable release :) )

**Comment by psifertex** [comment]
Thanks -- whenever the next release is cut we'll update it in the plugin manager.
