### ISSUE TITLE
Broken HexViewWidget

### ISSUE THREAD

**Issue by mink-fr** [borzacchiello/seninja#8]
Cheers,

When trying to select an area in the memory widget, I get a lot of those in the logs...
And I can't seem to be able to right click like in the demo video https://www.youtube.com/watch?v=jBr5Mb5HrZM
at 2min51... 
(I'm using Binary Ninja Version: 3.3.3996 Personal, e34a955e / Platform: Kali GNU/Linux Rolling)

``` 
Traceback (most recent call last):
  File "/home/user/.binaryninja/plugins/seninja/ui/hexview.py", line 434, in focusOutEvent
    if not event.reason() & Qt.MenuBarFocusReason:
TypeError: unsupported operand type(s) for &: 'FocusReason' and 'FocusReason'
```
```
Traceback (most recent call last):
  File "/home/user/.binaryninja/plugins/seninja/ui/hexview.py", line 420, in mousePressEvent
    self.leftMousePressed.emit(event)
TypeError: leftMousePressed() only accepts 0 argument(s), 1 given!

```

and tons of those (because it moves over lots of places):
```
Traceback (most recent call last):
  File "/home/user/.binaryninja/plugins/seninja/ui/hexview.py", line 425, in mouseMoveEvent
    self.leftMouseMoved.emit(event)
TypeError: leftMouseMoved() only accepts 0 argument(s), 1 given!

```

Please let me know if you need more.

**Comment by mink-fr** [comment]
I'm not knowledgeable, so don't take my word for it, but changing lines like 
`blablabla = Signal([something])`
to 
`blablabla = Signal(something)`
seemed to fix my issue. (up until now)

**Comment by borzacchiello** [comment]
Hi, thank you for pointing the issue out.
It seems that HexViewWidget is broken, probably when I switched from PyQt5 to PyQt6.

As you pointed out I am passing the wrong parameters to Signal, but it is not the only issue. Selecting something on the widget makes binaryninja crash.
I'll try to fix the issue in the following days.

**Comment by mink-fr** [comment]
"it is not the only issue" : to be honest, I haven't been able to use the plugin... I thought I was just noobing around during the ctf I was doing.
